[package]
name = "wasm-crypto"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ml-dsa = "0.0.4"
sha3 = "0.10.8"
ml-kem = { version = "0.2.1", features = ["deterministic"] }
wasm-bindgen = "0.2"
rand = "0.8"
getrandom = { version = "0.2.16", features = ["js"] }
