name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        
    - name: Install wasm-pack
      run: |
        WASM_PACK_VERSION=0.13.1
        curl -L "https://github.com/rustwasm/wasm-pack/releases/download/v${WASM_PACK_VERSION}/wasm-pack-v${WASM_PACK_VERSION}-x86_64-unknown-linux-musl.tar.gz" | tar -xz
        sudo mv wasm-pack-v${WASM_PACK_VERSION}-x86_64-unknown-linux-musl/wasm-pack /usr/local/bin/
        
    - name: Test Rust build
      run: |
        cargo build --target wasm32-unknown-unknown --release
        
    - name: Test wasm-pack build
      run: |
        wasm-pack build --target web --out-dir pkg --release
        
    - name: Verify package structure
      run: |
        ls -la pkg/
        cat pkg/package.json